In [5]:
import numpy as np

In [6]:
v1= np.array([1, 3, 5, 7, 9, 7, 5, 3, 1])

In [10]:
v2= v1.reshape(3, 3)

In [12]:
print(v2.shape)
print(v2)

(3, 3)
[[1 3 5]
 [7 9 7]
 [5 3 1]]


In [13]:
print(np.amax(v2, axis=1))

[5 9 5]


In [14]:
print(np.mean(v2, axis=0))

[4.33333333 5.         4.33333333]
