In [15]:
import numpy as np

In [16]:
v1= np.array([1, 3, 5, 7, 9, 7, 5, 3, 1])

In [17]:
v2= v1.reshape(3, 3)

In [18]:
print(v2.shape)
print(v2)

(3, 3)
[[1 3 5]
 [7 9 7]
 [5 3 1]]


In [19]:
row_max= np.amax(v2, axis=1)
print(row_max)

[5 9 5]


In [20]:
col_avg= np.mean(v2, axis=0)
print(col_avg)

[4.33333333 5.         4.33333333]
